### ISSUE TITLE
1.0 Final support?

### ISSUE THREAD

**Issue by jayphelps** [charlesjolley/node-ember#13]
Any plans to continue to support this repo or possibly add this ability directly to Ember core so two projects don't need to be maintained?

**Comment by charlesjolley** [comment]
Hi - I reassigned the node-ember NPM package to the emberjs Core Team. I assume they are going to publish a new version.  Unfortunately they made some changes to their toolchain on the way to 1.0 that broke my system so I can'y easily update it; we all have to wait on them to get it done.
