### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by juriejan** [charlesjolley/node-ember#14]
Would be real nice if the NPM package can reflect the latest version of Ember. Any chance that'll be happening soon?

**Comment by justinsoliz** [comment]
I would be interested in that as well

**Comment by charlesjolley** [comment]
Hi - I no longer own the ember package on NPM. the EmberJS project asked me to give it to them quite a long time ago with the intent of updating but I guess never got around to it.

@wycats, @tomdale - any plans to update the ember NPM module?

**Comment by waltz** [comment]
Is there any news on the Ember/NPM front? I'd love to use the NPM package via Browserify for a new project I'm working on but it's hard when it's this stale. Is there a way I can help out?

**Comment by charlesjolley** [comment]
Hi please talk to @wycats or @tomdale. I transferred ownership of this project to them sometime ago but they haven't updated it.

**Comment by b-long** [comment]
@wycats @tomdale @emberjs So... are you guys anti gulp + browserify or is it just accidental that n node-ember hasn't been updated?  [jens-a-e](https://github.com/jens-a-e/node-ember ) looks to have upgraded his version to ember @ 1.3.0, which might be a good place to continue these efforts.

**Comment by joedaniels29** [comment]
bump! @wycats or @tomdale 
I meant to upgrade my ember-cli repos and got this by mistake. `npm install ember` is the obvious thing to do when you want to get started with ember for the first time. any reason this is still here?
