### ISSUE TITLE
Handlebar Helpers not working

### ISSUE THREAD

**Issue by vizo** [charlesjolley/node-ember#2]
I can't figure out why "if" and "unless" helpers doesn't work. I require whole ember module in JS. Are they included in module?

**Comment by vizo** [comment]
I checked the source code of all modules and they are included... i think it must be something with handlebars compiler or it's configuration....

I get an error:
Uncaught TypeError: Object #<Object> has no method 'program'

It looks like something is missing in file after compiling but i can't figure it out.

Please help me ... I need to finish my project soon.

**Comment by pharcosyle** [comment]
Hey vizo, did you ever figure this out?

**Comment by vizo** [comment]
No :( I pulled down handlebars, built but it's same..

**Comment by pharcosyle** [comment]
Did you try not using the handlebars compiler?

'.hbr': require('ember/packager').HandlebarsCompiler

change to convoy.plugins.GenericCompiler maybe.

Also how has your experience with node-ember been so far. Are you experiencing issues you haven't experienced with plain ember?

**Comment by vizo** [comment]
I have no troubles with node-ember, no issues yet, just with handlebars helpers ...

If i change to convoy.plugins.GenericCompiler it doesn't work ...

**Comment by vizo** [comment]
I think i'm doing everything right, but it must be something wrong with packager.js file in node-ember. Looks like it doesn't include some code which have method "program" ...

**Comment by charlesjolley** [comment]
Hi - I looked into this. there is a bug in the Ember handlebars extensions that emits the wrong code during a compile. I know how to fix this so the feature will at least work, though it will technically be a little bit slower. I will look into it today.

**Comment by vizo** [comment]
Thank you very much ! :) I'm pulling my hairs for 4 days :D

**Comment by vizo** [comment]
Any progress? Sorry if i'm inpatient but i really need to implement this into my project.

**Comment by pharcosyle** [comment]
Hey Vizo, I've encountered the same problem: until our dear Charles fixes this I'm just including the ember templates in my markup with scripts, as descripbed in the docs

&lt;script type="text/x-handlebars" data-template-name="application"&gt;
...
&lt;/script&gt;

Not as nice as separate files but it works!

**Comment by vizo** [comment]
I know for this alternative solution, thanks for your care :) ... but the problem is that i already have a lot of templates in separate files ( before i used Rails for back-end and now I don't want to make my work double :)

**Comment by jtmoon** [comment]
I was wondering if there has been any progress on resolving this :)?

**Comment by vizo** [comment]
I wonder same :)

I made temporary solution. It doesn't precompile templates but at least you can serve templates in separated files and all helpers works as expected.

Make file Handlebars.js and put inside ...

``` javascript
require('ember/handlebars');
var FS = require('fs');

// Output Handlebars templates when used with a convoy pipeline
function Handlebars(asset, context, done) {
  FS.readFile(asset.path, 'utf8', function(err, data) {
    if (err) return done(err);
    var data = data.replace(/(\r\n|\n|\r)/gm,'');
    asset.body = "module.exports = Ember.Handlebars.compile('" + data + "');";
    done();
  });
}

module.exports = Handlebars;
```

So in convoy pipeline instead of ...

``` javascript
...
    packager: 'javascript',
    compilers: {
      '.hbs': require('ember/packager').HandlebarsCompiler
...
```

use ...

``` javascript
...
    packager: 'javascript',
    compilers: {
      '.hbs': require('./Handlebars')
...
```

I hope somebody will find it useful until the problem is fixed.

**Comment by pharcosyle** [comment]
<-- is finding this useful

**Comment by jtmoon** [comment]
Thanks @vizo I'm finding it useful as well :)

**Comment by vizo** [comment]
You are welcome :)

**Comment by vizo** [comment]
Finally i figure it out... https://github.com/charlesjolley/node-ember/pull/3

You can pull from my fork in your package.json until this repo is not updated.

If you are interested, I made also support for minification of CSS and Stylus files

https://github.com/vizo/convoy.git
https://github.com/vizo/convoy-stylus.git

Enjoy :)

@charlesjolley Please update repos :)

**Comment by charlesjolley** [comment]
Thanks for this pull request! I'm merging all of these in and posting new versions to npm. Sorry i missed them a month back; I've been travelling quite a bit.

**Comment by vizo** [comment]
No problem. You welcome.
